//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace website
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullaniciBilgileri
    {
        public kullaniciBilgileri()
        {
            this.urun = new HashSet<urun>();
        }
    
        public string KullaniciAdi { get; set; }
        public string KullaniciSifre { get; set; }
        public string KullaniciMail { get; set; }
        public string KullaniciTelefon { get; set; }
        public string KullaniciAdres { get; set; }
        public string ReadMoreUrl { get; set; }
        public string LocLat { get; set; }
        public string LocLong { get; set; }
    
        public virtual ICollection<urun> urun { get; set; }
    }
}
