//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace website
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public string KullaniciAdi { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<int> Adet { get; set; }
    }
}
